# Generated by Django 3.2.7 on 2021-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('description', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Hospice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Hospice', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'What is Hospice?',
                'verbose_name_plural': 'What is Hospice?',
            },
        ),
    ]
