# Generated by Django 3.2.6 on 2021-09-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
