# Generated by Django 3.2.7 on 2021-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Address'),
        ),
    ]
