# Generated by Django 3.2.6 on 2021-08-30 13:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=250)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_uploads/')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
