# Generated by Django 3.2.7 on 2021-09-07 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-health-aide', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Home Health Aide Service',
                'verbose_name_plural': 'Home Health Aide',
            },
        ),
        migrations.CreateModel(
            name='Assistant_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/perosonal-care', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Personal Care Assistance (PCA) Service',
                'verbose_name_plural': 'Personal Care Assistance (PCA)',
            },
        ),
        migrations.CreateModel(
            name='Care_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-care-nursing', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Home Care Nursing (HCN) Service',
                'verbose_name_plural': 'Home Care Nursing (HCN)',
            },
        ),
        migrations.CreateModel(
            name='Companion_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/companion', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Companion Service',
                'verbose_name_plural': 'Companion',
            },
        ),
        migrations.CreateModel(
            name='Homemaking_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/homemaking-service', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Homemaking Services Service',
                'verbose_name_plural': 'Homemaking Services',
            },
        ),
        migrations.CreateModel(
            name='Hospice_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/hospice', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Hospice Service',
                'verbose_name_plural': 'Hospice',
            },
        ),
        migrations.CreateModel(
            name='Interpretive_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/interpretive', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Interpretive Services Service',
                'verbose_name_plural': 'Interpretive Services',
            },
        ),
        migrations.CreateModel(
            name='IV_Therapy_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/iv-therapy', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'IV Therapy Service',
                'verbose_name_plural': 'IV Therapy',
            },
        ),
        migrations.CreateModel(
            name='Living_Skills_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/independent-living', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Independent Living Skills (ILS) Service',
                'verbose_name_plural': 'Independent Living Skills (ILS)',
            },
        ),
        migrations.CreateModel(
            name='Nursing_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/skilled-nursing', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Skilled Nurse (SN) Service',
                'verbose_name_plural': 'Skilled Nurse (SN)',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500, verbose_name='Heading')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Respite_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/respite', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Respite Service',
                'verbose_name_plural': 'Respite',
            },
        ),
        migrations.CreateModel(
            name='Social_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/social-service', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Social Services Service',
                'verbose_name_plural': 'Social Services',
            },
        ),
        migrations.CreateModel(
            name='Therapy_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/therapy', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Therapy Service',
                'verbose_name_plural': 'Therapy',
            },
        ),
    ]
