# Generated by Django 3.2.6 on 2021-08-30 14:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/companion')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_Care_Nursing_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-care-nursing')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_Health_Aide_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-health-aide')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homemaking_Services_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/homemaking-service')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospice_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/hospice')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Independent_Living_Skills_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/independent-living')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interpretive_Services_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/interpretive')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='IV_Therapy_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/iv-therapy')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Care_Assistant_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/perosonal-care')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respite_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/respite')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skilled_Nurse_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/skilled-nursing')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_Services_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/social-service')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/therapy')),
                ('blog', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
