# Generated by Django 3.2.6 on 2021-08-30 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210830_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aid_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-health-aide', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Home Health Aide',
                'verbose_name_plural': 'Home Health Aide',
            },
        ),
        migrations.CreateModel(
            name='Assistant_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/perosonal-care', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Personal Care Assistance (PCA)',
                'verbose_name_plural': 'Personal Care Assistance (PCA)',
            },
        ),
        migrations.CreateModel(
            name='Care_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/home-care-nursing', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Home Care Nursing (HCN)',
                'verbose_name_plural': 'Home Care Nursing (HCN)',
            },
        ),
        migrations.CreateModel(
            name='Living_Skills_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/independent-living', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Independent Living Skills (ILS)',
                'verbose_name_plural': 'Independent Living Skills (ILS)',
            },
        ),
        migrations.CreateModel(
            name='Nursing_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Heading')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_uploads/skilled-nursing', verbose_name='Image')),
                ('blog', ckeditor.fields.RichTextField(verbose_name='Details of Service')),
            ],
            options={
                'verbose_name': 'Skilled Nurse (SN)',
                'verbose_name_plural': 'Skilled Nurse (SN)',
            },
        ),
        migrations.DeleteModel(
            name='Care_Nursing_Service',
        ),
        migrations.DeleteModel(
            name='Health_Aide_Service',
        ),
        migrations.DeleteModel(
            name='Indp_Living_Skills_Service',
        ),
        migrations.DeleteModel(
            name='Personal_Care_Assistant_Service',
        ),
        migrations.DeleteModel(
            name='Skilled_Nurse_Service',
        ),
        migrations.AlterModelOptions(
            name='companion_service',
            options={'verbose_name': 'Companion', 'verbose_name_plural': 'Companion'},
        ),
        migrations.AlterModelOptions(
            name='homemaking_service',
            options={'verbose_name': 'Homemaking Services', 'verbose_name_plural': 'Homemaking Services'},
        ),
        migrations.AlterModelOptions(
            name='hospice_service',
            options={'verbose_name': 'Hospice', 'verbose_name_plural': 'Hospice'},
        ),
        migrations.AlterModelOptions(
            name='interpretive_service',
            options={'verbose_name': 'Interpretive Services', 'verbose_name_plural': 'Interpretive Services'},
        ),
        migrations.AlterModelOptions(
            name='iv_therapy_service',
            options={'verbose_name': 'IV Therapy', 'verbose_name_plural': 'IV Therapy'},
        ),
        migrations.AlterModelOptions(
            name='respite_service',
            options={'verbose_name': 'Respite', 'verbose_name_plural': 'Respite'},
        ),
        migrations.AlterModelOptions(
            name='social_service',
            options={'verbose_name': 'Social Services', 'verbose_name_plural': 'Social Services'},
        ),
        migrations.AlterModelOptions(
            name='therapy_service',
            options={'verbose_name': 'Therapy', 'verbose_name_plural': 'Therapy'},
        ),
        migrations.AlterField(
            model_name='companion_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='companion_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/companion', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='companion_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='homemaking_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='homemaking_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/homemaking-service', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homemaking_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='hospice_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='hospice_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/hospice', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hospice_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='interpretive_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='interpretive_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/interpretive', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='interpretive_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='iv_therapy_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='iv_therapy_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/iv-therapy', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='iv_therapy_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='respite_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='respite_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/respite', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='respite_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='social_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='social_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/social-service', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='social_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='therapy_service',
            name='blog',
            field=ckeditor.fields.RichTextField(verbose_name='Details of Service'),
        ),
        migrations.AlterField(
            model_name='therapy_service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_uploads/therapy', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='therapy_service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='Heading'),
        ),
    ]
