# Generated by Django 3.2.6 on 2021-08-31 15:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210830_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Employee Benefit',
                'verbose_name_plural': 'Employee Benefits',
            },
        ),
        migrations.AlterModelOptions(
            name='aid_service',
            options={'verbose_name': 'Home Health Aide Service', 'verbose_name_plural': 'Home Health Aide'},
        ),
        migrations.AlterModelOptions(
            name='assistant_service',
            options={'verbose_name': 'Personal Care Assistance (PCA) Service', 'verbose_name_plural': 'Personal Care Assistance (PCA)'},
        ),
        migrations.AlterModelOptions(
            name='care_service',
            options={'verbose_name': 'Home Care Nursing (HCN) Service', 'verbose_name_plural': 'Home Care Nursing (HCN)'},
        ),
        migrations.AlterModelOptions(
            name='companion_service',
            options={'verbose_name': 'Companion Service', 'verbose_name_plural': 'Companion'},
        ),
        migrations.AlterModelOptions(
            name='homemaking_service',
            options={'verbose_name': 'Homemaking Services Service', 'verbose_name_plural': 'Homemaking Services'},
        ),
        migrations.AlterModelOptions(
            name='hospice_service',
            options={'verbose_name': 'Hospice Service', 'verbose_name_plural': 'Hospice'},
        ),
        migrations.AlterModelOptions(
            name='interpretive_service',
            options={'verbose_name': 'Interpretive Services Service', 'verbose_name_plural': 'Interpretive Services'},
        ),
        migrations.AlterModelOptions(
            name='iv_therapy_service',
            options={'verbose_name': 'IV Therapy Service', 'verbose_name_plural': 'IV Therapy'},
        ),
        migrations.AlterModelOptions(
            name='living_skills_service',
            options={'verbose_name': 'Independent Living Skills (ILS) Service', 'verbose_name_plural': 'Independent Living Skills (ILS)'},
        ),
        migrations.AlterModelOptions(
            name='nursing_service',
            options={'verbose_name': 'Skilled Nurse (SN) Service', 'verbose_name_plural': 'Skilled Nurse (SN)'},
        ),
        migrations.AlterModelOptions(
            name='respite_service',
            options={'verbose_name': 'Respite Service', 'verbose_name_plural': 'Respite'},
        ),
        migrations.AlterModelOptions(
            name='social_service',
            options={'verbose_name': 'Social Services Service', 'verbose_name_plural': 'Social Services'},
        ),
        migrations.AlterModelOptions(
            name='therapy_service',
            options={'verbose_name': 'Therapy Service', 'verbose_name_plural': 'Therapy'},
        ),
    ]
