# Generated by Django 3.2.6 on 2021-08-31 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210831_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_benefits',
            name='benefits',
            field=ckeditor.fields.RichTextField(verbose_name='Benefits'),
        ),
    ]
