# Generated by Django 3.2.6 on 2021-08-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_employee_benefits_benefits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_Benefits',
        ),
    ]
