# Generated by Django 3.2.6 on 2021-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_employee_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='assistant_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='care_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='companion_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='homemaking_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='hospice_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='interpretive_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='iv_therapy_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='living_skills_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='nursing_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='respite_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='social_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
        migrations.AddField(
            model_name='therapy_service',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub-Heading'),
        ),
    ]
