# Generated by Django 3.2.7 on 2021-09-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
    ]
