# Generated by Django 3.2.7 on 2021-09-07 08:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', ckeditor.fields.RichTextField(verbose_name='Areas With Their Services')),
            ],
            options={
                'verbose_name': 'Areas & Service',
                'verbose_name_plural': 'Areas & Services',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('slug', models.SlugField(default='null', unique=True)),
                ('branch_address', models.CharField(max_length=20000, verbose_name='Embeded Google Map Link')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('team_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Employee_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1024, verbose_name='What Benefit?')),
                ('benefits', ckeditor.fields.RichTextField(verbose_name='Benefits')),
            ],
            options={
                'verbose_name': 'Employee Benefit',
                'verbose_name_plural': 'Employee Benefits',
            },
        ),
        migrations.CreateModel(
            name='Job_Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225, verbose_name='Job Title')),
                ('job_description', ckeditor.fields.RichTextField(verbose_name='Job Description and Areas')),
            ],
            options={
                'verbose_name': 'Job Opening',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Employee')),
                ('image', models.ImageField(upload_to='team/')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation of Employee')),
                ('working_on', models.CharField(max_length=255, verbose_name='Working in Row')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='career.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Apply_Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Date of Application')),
                ('position', models.CharField(max_length=10, verbose_name='Position(s) Applied For')),
                ('about', models.CharField(choices=[('radio', 'Radio'), ('friends', 'Friend'), ('website', 'Website'), ('ads', 'ADS'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('others', 'Others')], max_length=255, verbose_name='How did you hear about us?')),
                ('reffer', models.CharField(max_length=255, verbose_name='If reffered by other employ please enter the name below.')),
                ('under_18', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('does-not-apply', 'Does Not Apply')], max_length=15, verbose_name='If you are under 18 can you provide proof of your eligibility of work?')),
                ('other_company_work', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Hove you worked for our company?')),
                ('employeed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Are you currently Employed?')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='null', max_length=1024, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('available', models.DateField(verbose_name='On what date could you be avilable for work?')),
                ('travel', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=15, verbose_name='Can you travel if your job requires it?')),
                ('cv', models.FileField(upload_to='Application-forms/cv/', verbose_name='CV')),
                ('signature', models.FileField(upload_to='Application-forms/signature/', verbose_name='Digital Signature')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='career.branch', verbose_name='Branch applying for')),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
            },
        ),
    ]
