# Generated by Django 3.2.6 on 2021-09-01 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', ckeditor.fields.RichTextField(verbose_name='Benefits')),
            ],
            options={
                'verbose_name': 'Employee Benefit',
                'verbose_name_plural': 'Employee Benefits',
            },
        ),
    ]
