# Generated by Django 3.2.6 on 2021-09-01 07:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225, verbose_name='Job Title')),
                ('job_description', ckeditor.fields.RichTextField(verbose_name='Job Description')),
            ],
            options={
                'verbose_name': 'Job Opening',
            },
        ),
    ]
