# Generated by Django 3.2.6 on 2021-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Employee')),
                ('branch', models.CharField(max_length=255, verbose_name='Area of Branch')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation of Employee')),
                ('working_on', models.CharField(max_length=255, verbose_name='Working in Row')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Areas & Service', 'verbose_name_plural': 'Areas & Services'},
        ),
    ]
