# Generated by Django 3.2.6 on 2021-09-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20210901_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team/'),
            preserve_default=False,
        ),
    ]
