# Generated by Django 3.2.6 on 2021-09-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('branch_address', models.CharField(max_length=20000, verbose_name='Embeded Google Map Link')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('team_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='career.branch', verbose_name='Branch'),
        ),
    ]
