# Generated by Django 3.2.6 on 2021-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20210901_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_slug',
            field=models.SlugField(default='null', max_length=255),
        ),
    ]
