# Generated by Django 3.2.6 on 2021-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_branch_branch_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_slug',
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default=11, unique=True),
            preserve_default=False,
        ),
    ]
