# Generated by Django 3.2.6 on 2021-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_auto_20210901_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(default='null', unique=True),
        ),
    ]
