# Generated by Django 3.2.7 on 2021-09-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_alter_branch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_benefits',
            name='heading',
            field=models.CharField(default='nul', max_length=1024, verbose_name='What Benefit?'),
            preserve_default=False,
        ),
    ]
