# Generated by Django 3.2.7 on 2021-09-06 22:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_employee_benefits_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_opening',
            name='job_description',
            field=ckeditor.fields.RichTextField(verbose_name='Job Description and Areas'),
        ),
        migrations.CreateModel(
            name='Apply_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='Date of Application')),
                ('position', models.CharField(max_length=10, verbose_name='Position(s) Applied For')),
                ('about', models.CharField(max_length=10, verbose_name='How did you hear about us?')),
                ('reffer', models.CharField(max_length=255, verbose_name='If reffered by other employ please enter the name below.')),
                ('under_18', models.CharField(max_length=5, verbose_name='If you are under 18 can you provide proof of your eligibility of work?')),
                ('other_company_work', models.CharField(max_length=5, verbose_name='Hove you worked for our company?')),
                ('employeed', models.CharField(max_length=5, verbose_name='Are you currently Employed?')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='null', max_length=1024, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('available', models.DateTimeField(verbose_name='On what date could you be avilable for work?')),
                ('travel', models.CharField(max_length=5, verbose_name='Can you travel if your job requires it?')),
                ('cv', models.FileField(upload_to='cv/', verbose_name='CV')),
                ('signature', models.FileField(upload_to='signature/', verbose_name='Digital Signature')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='career.branch', verbose_name='Branch applying for')),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
            },
        ),
    ]
