# Generated by Django 3.2.7 on 2021-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_auto_20210907_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_forms',
            name='about',
            field=models.CharField(choices=[('radio', 'Radio'), ('friends', 'Friend'), ('website', 'Website'), ('ads', 'ADS'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('others', 'Others')], max_length=255, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='apply_forms',
            name='employeed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Are you currently Employed?'),
        ),
        migrations.AlterField(
            model_name='apply_forms',
            name='other_company_work',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='Hove you worked for our company?'),
        ),
        migrations.AlterField(
            model_name='apply_forms',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='apply_forms',
            name='travel',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=15, verbose_name='Can you travel if your job requires it?'),
        ),
        migrations.AlterField(
            model_name='apply_forms',
            name='under_18',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('does-not-apply', 'Does Not Apply')], max_length=15, verbose_name='If you are under 18 can you provide proof of your eligibility of work?'),
        ),
    ]
