# Generated by Django 3.2.7 on 2021-09-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_auto_20210907_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply_Forms',
            new_name='Apply_Now',
        ),
    ]
