# Generated by Django 3.2.7 on 2021-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0014_rename_apply_forms_apply_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_now',
            name='cv',
            field=models.FileField(upload_to='', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='apply_now',
            name='signature',
            field=models.FileField(upload_to='', verbose_name='Digital Signature'),
        ),
    ]
