# Generated by Django 3.2.7 on 2021-09-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_auto_20210907_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_now',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='apply_now',
            name='signature',
        ),
    ]
