# Generated by Django 3.2.7 on 2021-09-07 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_auto_20210907_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_now',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='CV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply_now',
            name='signature',
            field=models.FileField(default=1, upload_to='', verbose_name='Digital Signature'),
            preserve_default=False,
        ),
    ]
