# Generated by Django 3.2.7 on 2021-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0017_auto_20210907_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_now',
            name='cv',
            field=models.FileField(upload_to='cv/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='apply_now',
            name='signature',
            field=models.FileField(upload_to='signature/', verbose_name='Digital Signature'),
        ),
    ]
